# cribbed from deploy1.yml from dapp-card-store
# TODO: cache node modules?

name: Deploy Treasury Dapp

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
    - name: Checkout agoric-sdk
      uses: actions/checkout@v2
      with:
        repository: Agoric/agoric-sdk
        path: agoric-sdk
    - name: yarn install in agoric-sdk
      run: yarn install
      working-directory: ./agoric-sdk
    - name: yarn build in agoric-sdk
      run: yarn build
      working-directory: ./agoric-sdk
    - name: yarn link agoric cli
      run: |
        yarn link-cli ~/bin/agoric
        echo "/home/runner/bin" >> $GITHUB_PATH
      working-directory: ./agoric-sdk

    - name: Check out dapp
      uses: actions/checkout@v2
      with:
        path: dapp
    - name: Agoric install in dapp
      run: agoric install
      working-directory: ./dapp
    - name: yarn build in dapp
      run: yarn build
      working-directory: ./dapp

    - name: Configure dapp
      run: |
        echo "$CONTRACT_CONFIG" >dapp/ui/src/generated/installationConstants.js
        echo "$API_CONFIG" >dapp/ui/src/generated/defaults.js
      env:
        CONTRACT_CONFIG: ${{ secrets.CONTRACT_CONFIG }}
        API_CONFIG: ${{ secrets.API_CONFIG }}
    - name: yarn build:react in dapp ui
      run: yarn build:react
      working-directory: ./dapp/ui

    - name: Deploy preview via Netlify
      if: ${{ github.ref != 'refs/heads/main' }}
#      uses: netlify/actions/cli@master
#      # https://github.com/netlify/actions/tree/master/cli
#      with:
#        args: deploy --dir=dapp/ui/build
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: dapp/ui/build
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Publish to production via Netlify
      uses: netlify/actions/cli@master
      if: ${{ github.ref == 'refs/heads/main' }}
      # https://github.com/netlify/actions/tree/master/cli
      with:
        args: deploy --dir=dapp/ui/build --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
